baseURL = 'https://nathan.day.ag/'
languageCode = 'en-gb'
title = 'Nathan Day'
theme = 'hugo-coder'
enableEmoji = true

[pagination]
pagerSize = 10

[markup.highlight]
noClasses = false
style = "github-dark"

[markup.goldmark.renderer]
unsafe = true

[params]
description = "Nathan Day's personal website"
keywords = "blog,developer,personal,tinkerer"

avatarURL = "images/avatar.jpg"
dateFormat = "January 2, 2006"
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5
customCSS = ["css/home-content.css", "css/nostr-social.css", "css/list-layout.css"]

[params.umami]
siteID = "98a4f246-3482-4055-a059-78ae57d9a1ca"
scriptURL = "https://umami.btcmap.org/script.js"

[params.nostr]
enabled = true
enable_notes = true
enable_articles = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[[params.social]]
name = "GitHub"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/dadofsambonzuki/"

[[params.social]]
name = "X"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 3
url = "https://x.com/nathan_day/"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/nathanjamesday/"

[[params.social]]
name = "Email"
icon = "fa-solid fa-envelope fa-2x"
weight = 5
url = "mailto:nathan@day.ag"

[[params.social]]
name = "Lightning"
icon = "fa-solid fa-bolt fa-2x"
weight = 6
url = "lightning://nathan@day.ag"

[[params.social]]
name = "PGP Key"
icon = "fa-solid fa-key fa-2x"
weight = 7
url = "/nathan@day.ag.asc"

[[params.social]]
name = "Nostr"
svg = "/images/nostr-icon.svg"
weight = 4
url = "https://nosta.me/nprofile1qqsvfa085adgecmg84ffelcxx6zrn3ffu5jrc6cjtwng0zge3ptv43c82kf5d"

[[menu.main]]
name = "Projects"
weight = 1
url = "projects/"

[[menu.main]]
name = "Presentations"
weight = 2
url = "presentations/"

[[menu.main]]
name = "Podcasts"
weight = 3
url = "podcasts/"

[[menu.main]]
name = "Articles"
weight = 4
url = "articles/"

[[menu.main]]
name = "Notes"
weight = 5
url = "notes/"

[[menu.main]]
name = "Tags"
weight = 6
url = "tags/"

# Disabled - Articles now provides blog functionality
# [[menu.main]]
# name = "Blog"
# weight = 7
# url = "posts/"
