baseURL = 'https://nathan.day.ag/'
languageCode = 'en-gb'
title = 'Nathan Day'
theme = 'hugo-coder'
enableEmoji = true

[pagination]
pagerSize = 10

[markup.highlight]
noClasses = false
style = "github-dark"

[markup.goldmark.renderer]
unsafe = true

[params]
author = "Nathan Day"
description = "Nathan Day's personal website"
keywords = "blog,developer,personal,tinkerer"
info = ["Tinkerer"]
avatarURL = "images/avatar.jpg"
dateFormat = "January 2, 2006"
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "GitHub"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/dadofsambonzuki/"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/nathanjamesday/"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 3
url = "https://twitter.com/nathan_day/"

[[params.social]]
name = "Email"
icon = "fa-solid fa-envelope fa-2x"
weight = 4
url = "mailto:nathan@day.ag"

[[params.social]]
name = "Nostr"
icon = "fa-solid fa-bolt fa-2x"
weight = 5
url = "https://njump.me/nathan@day.ag"

[[menu.main]]
name = "About"
weight = 1
url = "about/"

[[menu.main]]
name = "Blog"
weight = 2
url = "posts/"
